### ISSUE TITLE
IndexError in plot.py

### ISSUE THREAD

**Issue by VincentMeilinger** [yardenas/la-mbda#3]
Dear Mr. As, 
I would like to use safe RL agent for my seminar project, but I ran into an issue with the provided example in your README.md.
This could very well be my fault, but I would be very happy if you could help me out!

### Setup 
I installed the necessary dependencies in an anaconda environment as described, but I had to install mujoco200 and dm_hack (https://github.com/yardenas/safety-gym/tarball/dm_hack) manually.

### Problem
I get the following error executing `python3 experiments/plot.py --data_path results/`:
```
Traceback (most recent call last):
  File "experiments/plot.py", line 287, in <module>
    summarize_experiments(args)
  File "experiments/plot.py", line 234, in summarize_experiments
    experiment_statistics['objectives_median'][-1],
IndexError: index -1 is out of bounds for axis 0 with size 0
```
And furthermore get the following warning:
```
Not all metrics are available!
```

### Steps to reproduce
- Run the given example:
```
python3 experiments/train.py --log_dir results/point_goal2/314 --environment sgym_Safexp-PointGoal2-v0 --total_training_steps 1000000 --safety
```
- Run plot.py as provided:
```
python3 experiments/plot.py --data_path results/
```

**Comment by yardenas** [comment]
Hi @VincentMeilinger, thanks for your interest.

Sure, I'd be happy to help. My hunch is that the issue relates to the (somewhat too strict) directory structure that the `plot.py` requires.

Can you please verify that you have following structure?
```
results
├── algo1
│   └── environment1
│       └── experiment1
│       └── ...
│   └── ...
└── algo2
    └── environment1
        ├── experiment1
        └── experiment2
```

**Comment by VincentMeilinger** [comment]
Hey,
Thank you so much for the quick reply!

The current file structure created by running the given example code looks as follows:
```
results
└── point_goal2
    └── 341
        └── agent_data
        └── events.out.tfevents...
        └── events.out.tfevents...
        └── params.txt
```
If I manually change it to:
```
results
└── la_mbda
     └── point_goal2
          └── 341
               └── ...
```
I get a `KeyError`:
```
Processing experiment results/la_mbda/point_goal2...
Environment:  point_goal2
Traceback (most recent call last):
  File "experiments/plot.py", line 288, in <module>
    summarize_experiments(args)
  File "experiments/plot.py", line 233, in summarize_experiments
    steps[resolve_environment(environment)]))
KeyError: ''
```

**Comment by yardenas** [comment]
I assume the following line
```
Environment:  point_goal2
```
is based on code that you added, correct?

I reran the code on my experiment results and it seems to work, so I'm trying to understand what are the difference.

Seems like the function [`resolve_environment`](https://github.com/yardenas/la-mbda/blob/17304eabb51aabd3eed43867277ee6a00ec42ce8/experiments/plot.py#L148) returns an empty string (while it should return [`'PointGoal2'`](https://github.com/yardenas/la-mbda/blob/17304eabb51aabd3eed43867277ee6a00ec42ce8/experiments/plot.py#L152)). Can you try debugging the input when it get's called?

**Comment by VincentMeilinger** [comment]
Thank you for the hint about the `resolve_environment` function. I noticed that I accidentally changed the function while refactoring the algorithm folder in my IDE. 

I removed all of my previous code changes. The only changes are now lowered training steps and episode length, which should not have an impact on my problem. Unfortunately, this still does not fix my error. I noticed that when running your given example, the constructed folder structure is this:
```
results
└── point_goal2
    └── 341
        └── agent_data
        └── events.out.tfevents...
        └── params.txt
```
instead of this:
```
results
└── la_mbda
     └── point_goal2
          └── 341
               └── ...
```
This is probably because you have set `--log_dir results/point_goal2/314` in your example, which supposedly should be  `--log_dir results/la_mbda/point_goal2/314` (?).
With this adjustment, the `events.out.tfevents...` file can be parsed properly.

I now (again) get the following index error when running ` python3 experiments/plot.py --data_path results/`:
```
Processing experiment results/la_mbda/point_goal2...
Parsing event file results/la_mbda/point_goal2/314/events.out.tfevents.1673777737.pc-v
2023-01-15 11:17:25.959303: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Not all metrics are available!
Traceback (most recent call last):
  File "experiments/plot.py", line 278, in <module>
    summarize_experiments(args)
  File "experiments/plot.py", line 225, in summarize_experiments
    experiment_statistics['objectives_median'][-1],
IndexError: index -1 is out of bounds for axis 0 with size 0
```
This comes from `parse_experiment_data` returning empty arrays, because `parse_tf_event_file` returns empty arrays as well:
```
    if any(map(lambda metric: metric not in ea.scalars.Keys(),
               ['evaluation/average_return',
                'evaluation/average_cost_return',
                'training/episode_cost_return'])
           ):
        return [], [], [], []      # <--- here
```

I am not sure why, because printing out `ea.scalars.Keys()` gives:
``` 
['training/episode_return', 'training/episode_cost_return', 'training/average_return', 'training/average_episode_length', 'training/average_cost_return']
```

I hope this is not too confusing, and I apologize for the inconvenience!

**Comment by VincentMeilinger** [comment]
I actually managed to fix all errors, it runs now!
The problem was that I apparently set the number of training steps (per epoch, total, ...) too low, and I had to change `--log_dir results/point_goal2/314` to `--log_dir results/la_mbda/point_goal2/314`.
Thank you for your patience and your help!

**Comment by yardenas** [comment]
Thanks for the update! I'll fix the README file with your correction. Also, I wonder what would be the best way to signal users in case they use don't use enough training steps---I'd be happy if you could provide further details of the error.

Thanks and good luck!
